"""Add categories table

Revision ID: d506451a3a2f
Revises: c37b2110c125
Create Date: 2025-06-17 22:29:40.581747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd506451a3a2f'
down_revision: Union[str, None] = 'c37b2110c125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('color', sa.String(), nullable=True))
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('category', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('todos', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'category_id')
    op.alter_column('category', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('category', 'color')
    # ### end Alembic commands ###
