"""update link model

Revision ID: 3d1a87084970
Revises: 8e7cbd4c07bc
Create Date: 2025-06-25 13:52:03.170012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1a87084970'
down_revision: Union[str, None] = '8e7cbd4c07bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('unique_parent_child_link', 'links', ['todolist_id_parent', 'todolist_id_child'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_parent_child_link', 'links', type_='unique')
    op.drop_column('links', 'created_at')
    # ### end Alembic commands ###
