"""add todolist_link

Revision ID: 8e7cbd4c07bc
Revises: 4763cfcd3d10
Create Date: 2025-06-25 13:33:50.629060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7cbd4c07bc'
down_revision: Union[str, None] = '4763cfcd3d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todolist_id_parent', sa.Integer(), nullable=False),
    sa.Column('todolist_id_child', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['todolist_id_child'], ['todolist.id'], ),
    sa.ForeignKeyConstraint(['todolist_id_parent'], ['todolist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
