"""Update level to priority field

Revision ID: c37b2110c125
Revises: f69df965fd01
Create Date: 2025-06-09 17:58:03.080291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37b2110c125'
down_revision: Union[str, None] = 'f69df965fd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.Integer(), nullable=True))
    op.drop_column('todos', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
