"""categorey fk changed

Revision ID: e1480fc92083
Revises: 41eda53f82ec
Create Date: 2025-06-18 15:46:01.587748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1480fc92083'
down_revision: Union[str, None] = '41eda53f82ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolist', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todolist', 'categories', ['category_id'], ['id'])
    op.drop_constraint(op.f('todos_category_id_fkey'), 'todos', type_='foreignkey')
    op.drop_column('todos', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('todos_category_id_fkey'), 'todos', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'todolist', type_='foreignkey')
    op.drop_column('todolist', 'category_id')
    # ### end Alembic commands ###
