"""Add is_active category

Revision ID: f2548e99db0e
Revises: dd87f75341f3
Create Date: 2025-06-18 11:51:40.528836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2548e99db0e'
down_revision: Union[str, None] = 'dd87f75341f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('categories', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('todos', 'todolist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todolist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('categories', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
